import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@exmaple.com",
      password: bcrypt.hashSync("654321"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      isFeatured: true,
      featuredImage: "/images/banner2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Classic Top",
      slug: "classic-top",
      category: "Top",
      image: "/images/women1.jpg",
      price: 100,
      brand: "Casely",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "A popular top",
    },
    {
      name: "Classic Coat",
      slug: "classic-coat",
      category: "Coat",
      image: "/images/women2.jpg",
      price: 200,
      brand: "H & M",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "A popular coat",
    },
    {
      name: "Classic Sweater",
      slug: "classic-swaeater",
      category: "Sweater",
      image: "/images/women6.jpg",
      price: 200,
      brand: "Zara",
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: "A popular sweater",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Long Top",
      slug: "long-top",
      category: "Top",
      image: "/images/women9.jpeg",
      price: 180,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular top",
    },

    {
      name: "Classic Suit",
      slug: "classic-suit",
      category: "Suit",
      image: "/images/women5.jpeg",
      price: 220,
      brand: "H & M",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular suit",
    },
    {
      name: "Classic Dress",
      slug: "classic-dress",
      category: "Dress",
      image: "/images/women3.jpeg",
      price: 120,
      brand: "Zara",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular dress",
    },
  ],
};

export default data;
